### ISSUE TITLE
Rates using etherscan, instead our own node

### ISSUE THREAD

**Issue by tbocek** [ICOnator/ICOnator-backend#15]

**Comment by gsmachado** [comment]
@tbocek as far as I've seen the commit https://github.com/ICOnator/ICOnator-backend/commit/28ef318ea0d55c082806bb892a6aab6dde35fa87, we maybe should make some adaptation on the design.

As far as I've seen [here](https://github.com/ICOnator/ICOnator-backend/commit/28ef318ea0d55c082806bb892a6aab6dde35fa87#diff-24d72593fc43739aec2a910e455b83e8) and [here](https://github.com/ICOnator/ICOnator-backend/commit/28ef318ea0d55c082806bb892a6aab6dde35fa87#diff-57e05b85d4cec0ce653d5b52e04db6ae), the `BLOCK_NR_BITCOIN_QUEUE` and `BLOCK_NR_ETHEREUM_QUEUE` should not be a queue with many consumers attached to each. We need to have an intermediate “fanout exchange” that for each consumer the block published should be consumed by the consumers. You get what I mean?

With the current design, `consumer 1` will consume Block 123, and then, the `consumer 2` will consumer Block 124. Then, `consumer 1` will not receive the Block 124.

Or did I get something wrong?

**Comment by gsmachado** [comment]
So, I added a fix for that. :-)

**Comment by tbocek** [comment]
awesome!
